/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#800020',
        'on-primary': '#ffffff',
        background: '#f5f1df',
        'on-background': '#2b0b14',
        surface: '#faf8f0',
        'on-surface': '#2b0b14',
        'surface-variant': '#ebdcae',
        'on-surface-variant': '#58111a',
        outline: '#800020',
        'outline-variant': '#d9aab5',
        'primary-container': '#800020',
        'on-primary-container': '#ffffff',
        'secondary-container': '#eadeca',
        'on-secondary-container': '#58111a',
        burgundy: {
          50: '#fdf2f4',
          100: '#fbe5e8',
          200: '#f7cfd5',
          300: '#efabaf',
          400: '#e37785',
          500: '#d04961',
          600: '#b72e48',
          700: '#9b2039',
          800: '#800020', // Classic Royal Burgundy
          900: '#58111a',
          950: '#38070e',
        },
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '48px',
        xl: '80px',
      },
      fontFamily: {
        sans: ['Inter', 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'],
        serif: ['Inter', 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'],
        headline: ['Inter', 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'],
        body: ['Inter', 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'],
        swiss: ['Inter', 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg': ['56px', { lineHeight: '1.15', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['40px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['28px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['22px', { lineHeight: '1.35', fontWeight: '600' }],
        'title-md': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'title-sm': ['16px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '700' }],
        'label-md': ['13px', { lineHeight: '1.3', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '500' }],
        'caption': ['11px', { lineHeight: '1.3', fontWeight: '400' }],
      },
      maxWidth: {
        container: '1280px',
      },
    },
  },
  plugins: [],
}
